---
- name: my hello world
  become: yes # this makes the user to become root or sudo
  gather_facts: no
  hosts: all
  tasks:
    - name: check ping
      ping: 
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2 # name of the package to be installed
        state: present # can put absent if you want to remove the package
        update_cache: yes
      become: yes  # this makes the user to become root or sudo
    - name: Start service webserver, if not started
      ansible.builtin.service:
        name: apache2
        state: started
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html # this is the part where apache2 accepts its files being copied or written to it          